version: '3.9'

services:
  hash_generator:
    build:
      context: .
    restart: unless-stopped
    env_file:
      - .env.test
    ports:
      - "82:82"
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 82"
